### ISSUE TITLE
talkjs lib broke Firebase lib on iOS

### ISSUE THREAD

**Issue by zSoNz** [talkjs/talkjs-flutter#22]
After instilling talkjs lib, Firebase lib starts throwing this error on Firebase.initializeApp:

PlatformException(channel-error, Unable to establish connection on channel., null, null)

Here dependencies from my pubspec.yaml:

  firebase_core: ^2.3.0
  talkjs_flutter: ^0.6.0

**Comment by vickz84259** [comment]
Hey there, we don't use Firebase on iOS. So you need to ensure that `Firebase.initializeApp` is only called on Android, unless you use Firebase on your app for other things other than push notifications. Here's a [link](https://talkjs.com/docs/Features/Notifications/Mobile_Push_Notifications/Flutter/#register-push-notification-handlers) to our docs on how to have push notifications setup.

**Comment by zSoNz** [comment]
@vickz84259 , yeah but my team are using Firebase for other purposes, and this lib totally broke it because we don’t have opportunity to initialise Firebase app with Firebase.initializeApp function. So please fix it.

**Comment by vickz84259** [comment]
Can you confirm if you have the `flutter_apns.disable_swizzling` key in your `info.plist`? If you don't follow the step outlined [here](https://talkjs.com/docs/Features/Notifications/Mobile_Push_Notifications/Flutter/#using-other-firebase-services-on-ios-optional).

If you are still experiencing the issue regardless, do let me know.

**Comment by zSoNz** [comment]
@vickz84259 , but if I wanna use Firebase apns lib for my project?

**Comment by zSoNz** [comment]
I think you really need to move your notification lib to another repo, so any who want to use it, can integrate it separately.

**Comment by zSoNz** [comment]
Anyway. I fix this issue here #23, please merge it. Rn I'm gonna use my fork instead.

**Comment by vickz84259** [comment]
> @vickz84259 , but if I wanna use Firebase apns lib for my project?

You should be able to do so.  Our SDK shouldn't interfere with your Firebase usage whatsoever.

> I think you really need to move your notification lib to another repo, so any who want to use it, can integrate it separately.

Push notifications on TalkJS is an entirely opt in feature. Dart/Flutter does not support optional dependencies hence the need to have `flutter_apns_only` as a transitive dependency despite push notification being an optional feature. 

If you would like to rely on your own implementation of push notifications via webhooks from TalkJS, you can do so. Just make sure you don't enable push notifications for your user's [Sessions](https://talkjs.com/docs/Reference/Flutter_SDK/Session/#Session__constructor) and also don't call `Talk.registerPushNotificationHandlers`.

**Comment by zSoNz** [comment]
> > @vickz84259 , but if I wanna use Firebase apns lib for my project?
> 
> You should be able to do so. Our SDK shouldn't interfere with your Firebase usage whatsoever.
> 
> > I think you really need to move your notification lib to another repo, so any who want to use it, can integrate it separately.
> 
> Push notifications on TalkJS is an entirely opt in feature. Dart/Flutter does not support optional dependencies hence the need to have `flutter_apns_only` as a transitive dependency despite push notification being an optional feature.
> 
> If you would like to rely on your own implementation of push notifications via webhooks from TalkJS, you can do so. Just make sure you don't enable push notifications for your user's [Sessions](https://talkjs.com/docs/Reference/Flutter_SDK/Session/#Session__constructor) and also don't call `Talk.registerPushNotificationHandlers`.

Okay, sounds logical!

**Comment by vickz84259** [comment]
#23 has been merged. I'll be making a release for this later today.
