### ISSUE TITLE
Need customising webview color and keyboard color

### ISSUE THREAD

**Issue by Veronika-dev** [talkjs/talkjs-flutter#24]
Hello talkjs team!

I am working on an application and I have faced to some problems:
1) On screen loading or when I am scrolling the view up or down, I can see white background. I think it is webview background and I found some possible solutions [here](https://github.com/flutter/flutter/issues/29300#issuecomment-913523324) and [here](https://crizantlai.medium.com/flutter-how-to-make-webview-transparent-9e3ce25d8d0).  
2) My application is in dark mode but I can't open a keyboard in ChatBox using necessary styles. Global setting in `themeData` `brightness: Brightness.dark` doesn't help with the situation. I need to be able to change keyboard color to Brightness.dark.

Could you please help me and fix it as soon as possible?

Here is a video of the problem.
https://user-images.githubusercontent.com/24383434/214597541-e6ec7b2c-3850-453b-8b9c-33df5c3f1143.mp4

And part of my code (build):
```
  Widget build(BuildContext context) {
    final themeData = Theme.of(context);
    return Scaffold(
      appBar: AppBar(
        // title: Text(conversation?.subject ?? ''),
      ),
      body: Container(
        padding: const EdgeInsets.only(bottom: 20),
        color: themeData.scaffoldBackgroundColor,
        child: FutureBuilder(
          future: getChatBasicInfo(),
          builder: (_, snapshot) {
            if (!snapshot.hasData || session == null) {
              return Container();
            }
            return LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) => Column(
                children: <Widget>[
                  Visibility(
                    visible: !_chatBoxLoaded,
                    child: SizedBox(
                      width: min(constraints.maxWidth, constraints.maxHeight),
                      height: min(constraints.maxWidth, constraints.maxHeight),
                      child: Center(
                        child: SizedBox(
                          width: 16,
                          height: 16,
                          child: CircularProgressIndicator(
                            color: themeData.primaryColor,
                            strokeWidth: 2,
                          ),
                        ),
                      ),
                    ),
                  ),
                  Visibility(
                    maintainState: true,
                    visible: _chatBoxLoaded,
                    child: ConstrainedBox(
                      constraints: constraints,
                      child: ChatBox(
                        session: session!,
                        conversation: conversation,
                        theme: 'dark_theme',
                        onLoadingStateChanged: (state) {
                          setState(() {
                            _chatBoxLoaded = state == LoadingState.loaded;
                          });
                        },
                        messageField: const MessageFieldOptions(
                          enterSendsMessage: true,
                        ),
                        showChatHeader: false,
                      ),
                    ),
                  ),
                ],
              ),
            );
          },
        ),
      ),
    );
  }
```

**Comment by Veronika-dev** [comment]
Hey, any updates?

**Comment by bugnano** [comment]
Hi,
At the moment we're transitioning to a new WebView implementation, which will have a transparent background, and a colleague of mine is testing the dark theme keyboard issue.
We'll keep you updated when the new release with all the fixes will be released.

**Comment by Veronika-dev** [comment]
Hi, 
Thank you! I'm looking forward to getting news

**Comment by bugnano** [comment]
Hi,
We released version 0.7.0 of our Flutter SDK, please test it and let me know if it fixes these problems.

**Comment by Veronika-dev** [comment]
@bugnano Hi,
There is a transparent background, thank you. However the problem with light keyboard is still here.

Also you can see from the attached video that content doesn't scroll to the last message.

https://user-images.githubusercontent.com/24383434/218121814-ef661879-2736-43f5-ab05-0d0bb62ce335.mp4

**Comment by Veronika-dev** [comment]
Hi, any updates?

**Comment by vickz84259** [comment]
We have upgraded the underlying webview to fix the keyboard color issue. The release will happen shortly.
