### ISSUE TITLE
Need firebase versions update. iOS PlatformException while using Firebase (versions conflict)

### ISSUE THREAD

**Issue by Veronika-dev** [talkjs/talkjs-flutter#33]
Hey,

I use firebase core and firebase messaging in my app. It works fine in Android but there is an error in iOS:
`PlatformException(channel-error, unable to establish connection on channel., null, null)`

After some research I found that problem is in outdated versions and every solution included update of them.

I have the latest versions:
```
firebase_core: ^2.13.0
firebase_messaging: ^14.6.1
```

However your versions are different. When I removed your package, the error gone.

Could you please update versions of firebase_core and firebase_messaging to the latest? I hope it will help me.

Thank you.

**Comment by bugnano** [comment]
OK, Version 0.8.1 has the updated Firebase dependencies.
