### ISSUE TITLE
Firebase PlatformException(channel-error, unable to establish connection on channel., null, null)

### ISSUE THREAD

**Issue by silentl007** [talkjs/talkjs-flutter#34]
Hey,

I integrated firebase core and firebase messaging in my app. It works fine in Android but there is an error in iOS:
PlatformException(channel-error, unable to establish connection on channel., null, null)

After removing packages one by one, i discovered removal of talkjs_flutter solved the issue.
I am using the latest firebase_core: 2.14.0 and firebase_messaging: 14.6.3 with talkjs_flutter: 0.8.1

**Comment by bugnano** [comment]
Did you change your Info.plist file as described here?

https://talkjs.com/docs/Features/Notifications/Mobile_Push_Notifications/Flutter/#using-other-firebase-services-on-ios-optional

You need to do so in order to use Firebase on iOS.

**Comment by silentl007** [comment]
> Did you change your Info.plist file as described here?
> 
> https://talkjs.com/docs/Features/Notifications/Mobile_Push_Notifications/Flutter/#using-other-firebase-services-on-ios-optional
> 
> You need to do so in order to use Firebase on iOS.

**Comment by silentl007** [comment]
> Did you change your Info.plist file as described here?
> 
> https://talkjs.com/docs/Features/Notifications/Mobile_Push_Notifications/Flutter/#using-other-firebase-services-on-ios-optional
> 
> You need to do so in order to use Firebase on iOS.

worked when i added it, thanks
