### ISSUE TITLE
No push notifications until ChatBox widget created

### ISSUE THREAD

**Issue by lotekbard** [talkjs/talkjs-flutter#40]
Hello!

I have problem with push notifications on clean installation of my app.
I am testing on Android 12 and 13.

Case:

- create talkJs session
- create talkJs user
- assign talkJs user to talkJs session
- send message from another user to me
- **NO PUSH NOTIFICATION RECEIVED**

When I open my view where I return **ChatBox** with session and conversation then the push notifications are showing.
After that I can close and kill the app and next time I run it, it is working fine.
It looks like a bug on a "first run".

Can any1 check this behavior?
Thank you!

**Comment by bugnano** [comment]
Thank you for your bug report.

The behaviour that you reported is the intended one.

Unfortunately, at the moment we have a limitation where registering the push notifications to our backend requires creating a ChatBox.

**Comment by vickz84259** [comment]
This will be fixed once #43 is merged and released shortly.
