### ISSUE TITLE
Push notifications from another user

### ISSUE THREAD

**Issue by lotekbard** [talkjs/talkjs-flutter#41]
Hello!

I have problem with "too many" push notifications I shouldn't receive.
I am testing on Android 12 and 13.

Case:

- log in to my app with user_1
- create talkJs session
- chat with user_2
- log out from my app
- _session.dispose(); and _session = null;
- log in to my app with user_2
- create new talkJs session
- send message to another user
- **RECEIVING PUSH NOTIFICATIONS FROM MYSELF** and another user

Additionally all the push notifications messages are combined like they are sent from another user even if it's me.

Can any1 check this behavior or tell me how can I really kill the previous session?
Thank you!

**Comment by vickz84259** [comment]
Once #43 is merged and released (which is shortly) you'll be able to call [Session.unsetPushRegistration()](https://talkjs.com/docs/Reference/Flutter_SDK/Session/#Session__unsetPushRegistration) which will remove the device's token from being associated with the current user. Call this method as part of your logout flow.
