### ISSUE TITLE
http package version issue

### ISSUE THREAD

**Issue by JulesBer** [talkjs/talkjs-flutter#52]
When I upgrade talkjs_flutter sdk version to 0.10.0 from 0.2.1 I get this error : 

Because talkjs_flutter >=0.9.0 depends on http ^0.13.6 and mlc_concierge depends on http ^1.1.2, talkjs_flutter >=0.9.0 is forbidden.
So, because mlc_concierge depends on talkjs_flutter ^0.10.0, version solving failed.

I can't downgrade my version of http because of other dependencies.

**Comment by bugnano** [comment]
We just released `talkjs_flutter` version 0.10.1 which should work with your version of the `http` package
