### ISSUE TITLE
Conversation.sendMessage not implemented

### ISSUE THREAD

**Issue by dawid-niedzwiecki** [talkjs/talkjs-flutter#57]
<img width="836" alt="image" src="https://github.com/talkjs/talkjs-flutter/assets/19879399/49ab81ee-1dd7-4f81-9e12-23e86e652507">

The `Conversation.sendMessage` method is not yet implemented. When can we expect it to be implemented? Is there a workaround for now?

**Comment by bigblind** [comment]
Hi @dawid-niedzwiecki, thanks for reaching out.

We're working on exposing a consistent API that makes it easier for our mobile SDKs to implement stuff like this. In the meantime, your best bet is probably to use [our REST API](https://talkjs.com/docs/Reference/REST_API/Messages/#sending-messages) to send the message. You'll want to send a request to your own backend, and then from there, call our API.

I understand that this is annoying, and we have plans to make this a lot easier in the future.

**Comment by dawid-niedzwiecki** [comment]
Hi @bigblind, thanks for your response. That's a lot to do in order to programmatically send a message. Is there an ETA on when this will be implemented?

**Comment by dawid-niedzwiecki** [comment]
Hi @bigblind, it's been over a month now. Is there any progress on this issue?
