### ISSUE TITLE
Error with GTMSessionFetcher

### ISSUE THREAD

**Issue by rafalPiotrkowski** [talkjs/talkjs-flutter#66]
Hey Im having a trouble with "GTMSessionFetcher" in a talkJs package. Ive made a fork of talkJs flutter repository to update its `  talkjs_flutter_inappwebview: ^6.0.8` side of a pubspec.yaml to  flutter_inappwebview: ^6.1.3. In my project  I've added it to pubspec.yaml with a use of path parameter to my local repository. It gives me an error saying "CocoaPods could not find compatible versions for pod "GTMSessionFetcher":" as shown on the screen.
Version of other packages: 
  google_sign_in: ^6.1.5
  firebase_messaging: ^15.0.4
  flutter_qr_bar_scanner: ^3.0.2
![Zrzut ekranu 2024-09-30 o 15 45 38](https://github.com/user-attachments/assets/c0c89f20-9ae4-4946-a56b-40067ea1bfd3)

**Comment by vickz84259** [comment]
Hey there, the error you are showing has nothing to do with the `talkjs-flutter` SDK. The errors seem to be related to: `google_sign_in_ios`, `flutter_qr_bar_scanner` and `firebase_messaging`. Look at this [stackoverflow question](https://stackoverflow.com/questions/78426888/cocoapods-could-not-find-compatible-versions-for-pod-gtmsessionfetcher-core) and this [Github issue](https://github.com/flutter/flutter/issues/148116) for more information  on how to resolve your issue.

The common advice from both links is that you probably need to do a `flutter pub upgrade` as well as a `pod repo update`.

**Comment by vickz84259** [comment]
Closing this issue as it is not related to the `talkjs-flutter` SDK. Feel free to open another issue should you have issues related to integrating the `talkjs-flutter` SDK.
